---
# we can have text properties which specify what text to draw (think atlas, prelim, internal)
# NOTE indentation matters
#   # this one pulls in all of the reference that's pre-defined
#   texts:
#     - *atlas
#   # this one merges the &internal with the current hash so everything but the label is the same
#   texts:
#     - label: preliminary
#       <<: *internal
#   texts:
#     - x: <position>
#       y: <position>
#       font: <number> (for SetTextFont(...))
#       size: <number> (for SetTextSize(...))
#       label: <string> (what to actually say)
atlas: &atlas
  x: 0.225
  y: 0.88
  font: 73
  size: 25
  label: ATLAS

internal: &internal
  x: 0.35
  font: 43
  label: Internal
  <<: *atlas

atlasinternal: &atlasinternal
  - *atlas
  - *internal

# top level defines the label / grouping
# second level is a list of files under that group, one can also specify a wildcard to match files so they all get grouped
# third level specifies extra information for a given file such as plots to ignore
# groups:
#   - name: <group name>
#     files:
#       - <a file path or a file pattern to match a set of files>
#     styles:
#       <name of style>: <value for style>
#   - name: <group name>
#     files: [file1, file2, ...]
#     styles: {style1: val1, style2: val2, ...}

# styles are set on all hists associated with that group
# styles:
#   - drawstyle (passed into Draw(...), think 'same' or 'hist')
#   - legendstyle (passed into Legend(...), think 'F')
#   - markercolor (also set with 'color')
#   - markerstyle
#   - markersize
#   - fillcolor (also set with 'color')
#   - fillstyle
#   - linecolor (also set with 'color')
#   - linestyle
#   - linewidth
#   - color (sets markercolor, fillcolor, linecolor)

groups:
  - name: data
    files:
      - TA02_MBJ13V4-6/data_1L/fetch/data-optimizationTree/*.root
    styles:
      legendstyle: p
      color: black
    do not scale me: true

  - name: "t#bar{t}"
    files:
      - TA02_MBJ13V4-6/ttbarInc_1L/fetch/data-optimizationTree/*410000*.root
      - TA02_MBJ13V4-6/ttbarExc_1L/fetch/data-optimizationTree/*407012*.root
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: dijets
    files:
      - TA02_MBJ13V4-6/dijet_1L/fetch/data-optimizationTree/*.root
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: W+jets
    files:
      - TA02_MBJ13V4-6/Wsherpa_1L/fetch/data-optimizationTree/*.root
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: Z+jets
    files:
      - TA02_MBJ13V4-6/Zsherpa_1L/fetch/data-optimizationTree/*.root
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: single top
    files:
      - TA02_MBJ13V4-6/singletop_1L/fetch/data-optimizationTree/*.root
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: top EW
    files:
      - TA02_MBJ13V4-6/topEW_1L/fetch/data-optimizationTree/*.root
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

# plots:
#   config:  # here we set global configurations that are applied uniformly such as...
#     canvas:
#     legend:
#     texts:

plots:
  config:
    texts:
      - *atlas
      - *internal
      - &topline
        x: 0.25
        y: 0.84
        font: 43
        size: 18
        label: "#sqrt{s} = 13 TeV, L_{int} #approx 1.7 fb^{-1}"
    canvas:
      width: 650
      height: 500
      logy: true
      ndivisions: 505
    legend:
      leftmargin: 0.425
      topmargin: 0.025
      rightmargin: 0.075
      textsize: 14
      entrysep: 0.01
      entryheight: 0.02

  paths:
    n-1/CR-1/m_effective:
      rebin: 4
      canvas:
        logy: true
      texts:
        -
          y: 0.8
          label: "CR1"
          <<: *topline
      ymin: 0.01
      ymax: 30
      ylabel: events
      xlabel: "m_{eff}"
      ratio: true
    n-1/CR-1/met:
      rebin: 4
      canvas:
        logy: true
      texts:
        -
          y: 0.8
          label: "CR1"
          <<: *topline
      ymin: 0.01
      ymax: 300
      ylabel: events
      xlabel: "#slash{E}_{T}"
      ratio: true
    n-1/CR-1/multiplicity_jet:
      rebin: 1
      texts:
        -
          y: 0.8
          label: "CR1"
          <<: *topline
      ymin: 0.01
      ymax: 300
      ylabel: events
      xlabel: "# of jets"
      ratio: true
    n-1/CR-1/multiplicity_jet_b:
      rebin: 1
      texts:
        -
          y: 0.8
          label: "CR1"
          <<: *topline
      ymin: 0.01
      ymax: 300
      ylabel: events
      xlabel: "# of #it{b}-jets"
      xmin: 0
      xmax: 10
      ratio: true
    n-1/CR-1/multiplicity_topTag_veryloose:
      rebin: 1
      texts:
        -
          y: 0.8
          label: "CR1"
          <<: *topline
      ymin: 0.01
      ymax: 30
      ylabel: events
      xlabel: "# of tops (veryloose)"
      ratio: true
    n-1/CR-1/m_transverse:
      rebin: 1
      texts:
        -
          y: 0.8
          label: "CR1"
          <<: *topline
      ymin: 0.01
      ymax: 50
      ylabel: events
      xlabel: "m_{T}"
      ratio: true
    n-1/CR-2/m_effective:
      rebin: 4
      canvas:
        logy: true
      texts:
        -
          y: 0.8
          label: "CR2"
          <<: *topline
      ymin: 0.01
      ymax: 30
      ylabel: events
      xlabel: "m_{eff}"
      ratio: true
    n-1/CR-2/met:
      rebin: 4
      canvas:
        logy: true
      texts:
        -
          y: 0.8
          label: "CR2"
          <<: *topline
      ymin: 0.01
      ymax: 300
      ylabel: events
      xlabel: "#slash{E}_{T}"
      ratio: true
    n-1/CR-2/multiplicity_jet:
      rebin: 1
      texts:
        -
          y: 0.8
          label: "CR2"
          <<: *topline
      ymin: 0.01
      ymax: 300
      ylabel: events
      xlabel: "# of jets"
      ratio: true
    n-1/CR-2/multiplicity_jet_b:
      rebin: 1
      texts:
        -
          y: 0.8
          label: "CR2"
          <<: *topline
      ymin: 0.01
      ymax: 300
      ylabel: events
      xlabel: "# of #it{b}-jets"
      xmin: 0
      xmax: 10
      ratio: true
    n-1/CR-2/multiplicity_topTag_veryloose:
      rebin: 1
      texts:
        -
          y: 0.8
          label: "CR2"
          <<: *topline
      ymin: 0.01
      ymax: 30
      ylabel: events
      xlabel: "# of tops (veryloose)"
      ratio: true
    n-1/CR-2/m_transverse:
      rebin: 1
      texts:
        -
          y: 0.8
          label: "CR2"
          <<: *topline
      ymin: 0.01
      ymax: 50
      ylabel: events
      xlabel: "m_{T}"
      ratio: true
    n-1/CR-3/m_effective:
      rebin: 4
      canvas:
        logy: true
      texts:
        -
          y: 0.8
          label: "CR3"
          <<: *topline
      ymin: 0.01
      ymax: 30
      ylabel: events
      xlabel: "m_{eff}"
      ratio: true
    n-1/CR-3/met:
      rebin: 4
      canvas:
        logy: true
      texts:
        -
          y: 0.8
          label: "CR3"
          <<: *topline
      ymin: 0.01
      ymax: 300
      ylabel: events
      xlabel: "#slash{E}_{T}"
      ratio: true
    n-1/CR-3/multiplicity_jet:
      rebin: 1
      texts:
        -
          y: 0.8
          label: "CR3"
          <<: *topline
      ymin: 0.01
      ymax: 300
      ylabel: events
      xlabel: "# of jets"
      ratio: true
    n-1/CR-3/multiplicity_jet_b:
      rebin: 1
      texts:
        -
          y: 0.8
          label: "CR3"
          <<: *topline
      ymin: 0.01
      ymax: 300
      ylabel: events
      xlabel: "# of #it{b}-jets"
      xmin: 0
      xmax: 10
      ratio: true
    n-1/CR-3/multiplicity_topTag_veryloose:
      rebin: 1
      texts:
        -
          y: 0.8
          label: "CR3"
          <<: *topline
      ymin: 0.01
      ymax: 30
      ylabel: events
      xlabel: "# of tops (veryloose)"
      ratio: true
    n-1/CR-3/m_transverse:
      rebin: 1
      texts:
        -
          y: 0.8
          label: "CR3"
          <<: *topline
      ymin: 0.01
      ymax: 50
      ylabel: events
      xlabel: "m_{T}"
      ratio: true
    n-1/CR-4/m_effective:
      rebin: 4
      canvas:
        logy: true
      texts:
        -
          y: 0.8
          label: "CR4"
          <<: *topline
      ymin: 0.01
      ymax: 30
      ylabel: events
      xlabel: "m_{eff}"
      ratio: true
    n-1/CR-4/met:
      rebin: 4
      canvas:
        logy: true
      texts:
        -
          y: 0.8
          label: "CR4"
          <<: *topline
      ymin: 0.01
      ymax: 300
      ylabel: events
      xlabel: "#slash{E}_{T}"
      ratio: true
    n-1/CR-4/multiplicity_jet:
      rebin: 1
      texts:
        -
          y: 0.8
          label: "CR4"
          <<: *topline
      ymin: 0.01
      ymax: 300
      ylabel: events
      xlabel: "# of jets"
      ratio: true
    n-1/CR-4/multiplicity_jet_b:
      rebin: 1
      texts:
        -
          y: 0.8
          label: "CR4"
          <<: *topline
      ymin: 0.01
      ymax: 300
      ylabel: events
      xlabel: "# of #it{b}-jets"
      xmin: 0
      xmax: 10
      ratio: true
    n-1/CR-4/multiplicity_topTag_veryloose:
      rebin: 1
      texts:
        -
          y: 0.8
          label: "CR4"
          <<: *topline
      ymin: 0.01
      ymax: 30
      ylabel: events
      xlabel: "# of tops (veryloose)"
      ratio: true
    n-1/CR-4/m_transverse:
      rebin: 1
      texts:
        -
          y: 0.8
          label: "CR4"
          <<: *topline
      ymin: 0.01
      ymax: 50
      ylabel: events
      xlabel: "m_{T}"
      ratio: true
