---
# defines background groups for the cutflows
# wildcards for file patterns are allowed
# NOTE indentation matters
#
# ex. 
# backgrounds:
#   - name: dijets
#     files:
#       - *36102*.hists
#   - name: "t#bar{t}" 
#     files:
#       - *ttbar*.hists     
# 
backgrounds:

  - name: "dijet"
    files:
      - /Users/joakim/ewk/results/ewk_mbj_ntuples/histfitter/histograms/cutflow_MctbbG160_Wh_optimization_May20_400_0_everycut/*361021*.hists
      - /Users/joakim/ewk/results/ewk_mbj_ntuples/histfitter/histograms/cutflow_MctbbG160_Wh_optimization_May20_400_0_everycut/*361022*.hists
      - /Users/joakim/ewk/results/ewk_mbj_ntuples/histfitter/histograms/cutflow_MctbbG160_Wh_optimization_May20_400_0_everycut/*361023*.hists
      - /Users/joakim/ewk/results/ewk_mbj_ntuples/histfitter/histograms/cutflow_MctbbG160_Wh_optimization_May20_400_0_everycut/*361024*.hists
      - /Users/joakim/ewk/results/ewk_mbj_ntuples/histfitter/histograms/cutflow_MctbbG160_Wh_optimization_May20_400_0_everycut/*361025*.hists
      - /Users/joakim/ewk/results/ewk_mbj_ntuples/histfitter/histograms/cutflow_MctbbG160_Wh_optimization_May20_400_0_everycut/*361026*.hists
      - /Users/joakim/ewk/results/ewk_mbj_ntuples/histfitter/histograms/cutflow_MctbbG160_Wh_optimization_May20_400_0_everycut/*361027*.hists
      - /Users/joakim/ewk/results/ewk_mbj_ntuples/histfitter/histograms/cutflow_MctbbG160_Wh_optimization_May20_400_0_everycut/*361028*.hists

  - name: "diboson"
    files:
      - /Users/joakim/ewk/results/ewk_mbj_ntuples/histfitter/histograms/cutflow_MctbbG160_Wh_optimization_May20_400_0_everycut/*diboson*.hists

  - name: "ttbar"
    files:
      - /Users/joakim/ewk/results/ewk_mbj_ntuples/histfitter/histograms/cutflow_MctbbG160_Wh_optimization_May20_400_0_everycut/*ttbar*.hists

  - name: "singletop"
    files:
      - /Users/joakim/ewk/results/ewk_mbj_ntuples/histfitter/histograms/cutflow_MctbbG160_Wh_optimization_May20_400_0_everycut/*singletop*.hists

  - name: "ttbar+V"
    files:
      - /Users/joakim/ewk/results/ewk_mbj_ntuples/histfitter/histograms/cutflow_MctbbG160_Wh_optimization_May20_400_0_everycut/*topEW*.hists

  - name: "W+jets"
    files:
      - /Users/joakim/ewk/results/ewk_mbj_ntuples/histfitter/histograms/cutflow_MctbbG160_Wh_optimization_May20_400_0_everycut/*W_sherpa*.hists

  - name: "Z+jets"
    files:
      - /Users/joakim/ewk/results/ewk_mbj_ntuples/histfitter/histograms/cutflow_MctbbG160_Wh_optimization_May20_400_0_everycut/*Z_sherpa*.hists

# defined analogously for signal samples
# one group per signal sample is required
signals:

  - name: "m_C1/N2 = 150, m_N2 = 0"
    files:
      - /Users/joakim/ewk/results/ewk_mbj_ntuples/histfitter/histograms/cutflow_MctbbG160_Wh_optimization_May20_400_0_everycut/user.jolsson.mc15_13TeV.000010.MGPy8EG_A14N23LO_C1N2_Wh_150p0_0p0_bbqq_J10.DAOD_SUSY10.20170322_2.3.4.4_EXT0.merged.hists
    outfile: "cutflows_resolved/optimization_Wh_400_0_detailed_cutflow_masspoint_150_0.txt"

  - name: "m_C1/N2 = 300, m_N2 = 0"
    files:
      - /Users/joakim/ewk/results/ewk_mbj_ntuples/histfitter/histograms/cutflow_MctbbG160_Wh_optimization_May20_400_0_everycut/user.jolsson.mc15_13TeV.000009.MGPy8EG_A14N23LO_C1N2_Wh_300p0_0p0_bbqq_J10.DAOD_SUSY10.20170322_2.3.4.4_EXT0.merged.hists
    outfile: "cutflows_resolved/optimization_Wh_400_0_detailed_cutflow_masspoint_300_0.txt"

  - name: "m_C1/N2 = 300, m_N2 = 50"
    files:
      - /Users/joakim/ewk/results/ewk_mbj_ntuples/histfitter/histograms/cutflow_MctbbG160_Wh_optimization_May20_400_0_everycut/user.jolsson.mc15_13TeV.000016.MGPy8EG_A14N23LO_C1N2_Wh_300p0_50p0_bbqq_J10.DAOD_SUSY10.20170514_1.1.3.1_EXT0.merged.hists
    outfile: "cutflows_resolved/optimization_Wh_400_0_detailed_cutflow_masspoint_300_50.txt"

  - name: "m_C1/N2 = 300, m_N2 = 100"
    files:
      - /Users/joakim/ewk/results/ewk_mbj_ntuples/histfitter/histograms/cutflow_MctbbG160_Wh_optimization_May20_400_0_everycut/user.jolsson.mc15_13TeV.000008.MGPy8EG_A14N23LO_C1N2_Wh_300p0_100p0_bbqq_J10.DAOD_SUSY10.20170322_2.3.4.4_EXT0.merged.hists
    outfile: "cutflows_resolved/optimization_Wh_400_0_detailed_cutflow_masspoint_400_0.txt"

  - name: "m_C1/N2 = 350, m_N2 = 50"
    files:
      - /Users/joakim/ewk/results/ewk_mbj_ntuples/histfitter/histograms/cutflow_MctbbG160_Wh_optimization_May20_400_0_everycut/user.jolsson.mc15_13TeV.000017.MGPy8EG_A14N23LO_C1N2_Wh_350p0_50p0_bbqq_J10.DAOD_SUSY10.20170514_1.1.3.1_EXT0.merged.hists
    outfile: "cutflows_resolved/optimization_Wh_400_0_detailed_cutflow_masspoint_350_50.txt"

  - name: "m_C1/N2 = 350, m_N2 = 100"
    files:
      - /Users/joakim/ewk/results/ewk_mbj_ntuples/histfitter/histograms/cutflow_MctbbG160_Wh_optimization_May20_400_0_everycut/user.jolsson.mc15_13TeV.000018.MGPy8EG_A14N23LO_C1N2_Wh_350p0_100p0_bbqq_J10.DAOD_SUSY10.20170514_1.1.3.1_EXT0.merged.hists
    outfile: "cutflows_resolved/optimization_Wh_400_0_detailed_cutflow_masspoint_350_100.txt"

  - name: "m_C1/N2 = 400, m_N2 = 0"
    files:
      - /Users/joakim/ewk/results/ewk_mbj_ntuples/histfitter/histograms/cutflow_MctbbG160_Wh_optimization_May20_400_0_everycut/user.jolsson.mc15_13TeV.000019.MGPy8EG_A14N23LO_C1N2_Wh_400p0_0p0_bbqq_J10.DAOD_SUSY10.20170514_1.1.3.1_EXT0.merged.hists
    outfile: "cutflows_resolved/optimization_Wh_400_0_detailed_cutflow_masspoint_400_0.txt"

  - name: "m_C1/N2 = 450, m_N2 = 50"
    files:
      - /Users/joakim/ewk/results/ewk_mbj_ntuples/histfitter/histograms/cutflow_MctbbG160_Wh_optimization_May20_400_0_everycut/user.jolsson.mc15_13TeV.000021.MGPy8EG_A14N23LO_C1N2_Wh_450p0_50p0_bbqq_J10.DAOD_SUSY10.20170514_1.1.3.1_EXT0.merged.hists
    outfile: "cutflows_resolved/optimization_Wh_400_0_detailed_cutflow_masspoint_450_50.txt"

  - name: "m_C1/N2 = 500, m_N2 = 0"
    files:
      - /Users/joakim/ewk/results/ewk_mbj_ntuples/histfitter/histograms/cutflow_MctbbG160_Wh_optimization_May20_400_0_everycut/user.jolsson.mc15_13TeV.000007.MGPy8EG_A14N23LO_C1N2_Wh_500p0_0p0_bbqq_J10.DAOD_SUSY10.20170322_2.3.4.4_EXT0.merged.hists
    outfile: "cutflows_resolved/optimization_Wh_400_0_detailed_cutflow_masspoint_500_0.txt"

  - name: "m_C1/N2 = 500, m_N2 = 100"
    files:
      - /Users/joakim/ewk/results/ewk_mbj_ntuples/histfitter/histograms/cutflow_MctbbG160_Wh_optimization_May20_400_0_everycut/user.jolsson.mc15_13TeV.000006.MGPy8EG_A14N23LO_C1N2_Wh_500p0_100p0_bbqq_J10.DAOD_SUSY10.20170322_2.3.4.4_EXT0.merged.hists
    outfile: "cutflows_resolved/optimization_Wh_400_0_detailed_cutflow_masspoint_500_100.txt"

  - name: "m_C1/N2 = 600, m_N2 = 0"
    files:
      - /Users/joakim/ewk/results/ewk_mbj_ntuples/histfitter/histograms/cutflow_MctbbG160_Wh_optimization_May20_400_0_everycut/user.jolsson.mc15_13TeV.000014.MGPy8EG_A14N23LO_C1N2_Wh_600p0_0p0_bbqq_J10.DAOD_SUSY10.20170506_2.1.1.1_EXT0.merged.hists
    outfile: "cutflows_resolved/optimization_Wh_400_0_detailed_cutflow_masspoint_600_0.txt"

  - name: "m_C1/N2 = 800, m_N2 = 0"
    files:
      - /Users/joakim/ewk/results/ewk_mbj_ntuples/histfitter/histograms/cutflow_MctbbG160_Wh_optimization_May20_400_0_everycut/user.jolsson.mc15_13TeV.000012.MGPy8EG_A14N23LO_C1N2_Wh_800p0_0p0_bbqq_J10.DAOD_SUSY10.20170506_2.1.1.1_EXT0.merged.hists
    outfile: "cutflows_resolved/optimization_Wh_400_0_detailed_cutflow_masspoint_800_0.txt"

  - name: "m_C1/N2 = 800, m_N2 = 200"
    files:
      - /Users/joakim/ewk/results/ewk_mbj_ntuples/histfitter/histograms/cutflow_MctbbG160_Wh_optimization_May20_400_0_everycut/user.jolsson.mc15_13TeV.000011.MGPy8EG_A14N23LO_C1N2_Wh_800p0_200p0_bbqq_J10.DAOD_SUSY10.20170506_2.1.1.1_EXT0.merged.hists
    outfile: "cutflows_resolved/optimization_Wh_400_0_detailed_cutflow_masspoint_800_200.txt"

# specify the path to each cutflow histogram
# one cutflow is saved for each signal point (totw_cutflow.py with the '--detailed-cutflow 1' option
cutflows:
  paths:
    hists/all/cutflow:
      label: "All events"
    hists/default/cutflow:
      label: "Preselection"
    hists/optimization_400_0_nJetsEq4/cutflow:
      label: "N_jets = 4"
    hists/optimization_400_0_nJetsEq4_nBJetsGeq1Leq2/cutflow:
      label: "1 <= N_b-jets <= 2"
    hists/optimization_400_0_nJetsEq4_nBJetsGeq1Leq2_metG300/cutflow:
      label: "MET > 300 GeV"
    hists/optimization_400_0_nJetsEq4_nBJetsGeq1Leq2_metG300_MeffG1100/cutflow:
      label: "Meff > 1100 GeV"
    hists/optimization_400_0_nJetsEq4_nBJetsGeq1Leq2_metG300_MeffG1100_dphiSum4jetG2p6/cutflow:
      label: "dPhi(diboson,MET) > 2.6"
    hists/optimization_400_0_nJetsEq4_nBJetsGeq1Leq2_metG300_MeffG1100_dphiSum4jetG2p6_MctbbG160/cutflow:
      label: "Mctbb > 160 GeV"
    hists/optimization_400_0_nJetsEq4_nBJetsGeq1Leq2_metG300_MeffG1100_dphiSum4jetG2p6_MctbbG160_MinvbbG100L140/cutflow:
      label: "100 < M_bb/GeV < 140"
    hists/optimization_400_0_nJetsEq4_nBJetsGeq1Leq2_metG300_MeffG1100_dphiSum4jetG2p6_MctbbG160_MinvbbG100L140_MinvNonbbG60L110/cutflow:
      label: "60 < M_non_bb/GeV < 110"
